name: Java Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Lấy code từ repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Cài đặt JDK 17 (hoặc đổi theo version project của bạn)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Di chuyển vào thư mục backend và build bằng Maven Wrapper
      - name: Build with Maven
        working-directory: ./backend
        run: ./mvnw clean install

      # (Tùy chọn) chạy test luôn
      - name: Run tests
        working-directory: ./backend
        run: ./mvnw test
